### ISSUE TITLE
2.5.0 Doesn't work on 1.13

### ISSUE THREAD

**Issue by CaptainAmpersand** [SuperRonanCraft/BetterRTP#2]
```
[15:48:09 INFO]: MrAmpersand issued server command: /rtp
[15:48:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rtp' in plugin BetterRTP v2.5.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [server.jar:git-Spigot-69774b3-a0c7bcf]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [server.jar:git-Spigot-69774b3-a0c7bcf]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [server.jar:git-Spigot-69774b3-a0c7bcf]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [server.jar:git-Spigot-69774b3-a0c7bcf]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [server.jar:git-Spigot-69774b3-a0c7bcf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at me.SuperRonanCraft.BetterRTP.event.RTP.checkDepends(RTP.java:327) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.RTP.randomLoc(RTP.java:199) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.RTP.setup(RTP.java:121) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.RTP.start(RTP.java:73) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.Commands.tp(Commands.java:101) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.Commands.commandExecuted(Commands.java:73) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.Main.onCommand(Main.java:76) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.WGBukkit
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at me.SuperRonanCraft.BetterRTP.event.RTP.checkDepends(RTP.java:327) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.RTP.randomLoc(RTP.java:199) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.RTP.setup(RTP.java:121) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.RTP.start(RTP.java:73) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.Commands.tp(Commands.java:101) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.event.Commands.commandExecuted(Commands.java:73) ~[?:?]
        at me.SuperRonanCraft.BetterRTP.Main.onCommand(Main.java:76) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-69774b3-a0c7bcf]
        ... 15 more
```

**Comment by CaptainAmpersand** [comment]
I know you're rewriting it anyways, just wanted to let you know about this :P
CraftBukkit version git-Spigot-69774b3-a0c7bcf (MC: 1.13)
Minecraft 1.13 client
