### ISSUE TITLE
java.lang.NoClassDefFoundError: me/RonanCraft/Pueblos/resources/files/FileOther$FILETYPE

### ISSUE THREAD

**Issue by mrfloris** [SuperRonanCraft/BetterRTP#84]
**Plugin Version**:

**Describe The Bug**:

Starting up the server after upgrading from `BetterRTP-3.1.0-5.jar` to `BetterRTP-3.2.0.jar`
```
[12:27:12 WARN]: [BetterRTP] Plugin BetterRTP v3.2.0 generated an exception while executing task 75
java.lang.NoClassDefFoundError: me/RonanCraft/Pueblos/resources/files/FileOther$FILETYPE
        at me.SuperRonanCraft.BetterRTP.references.database.SQLite.load(SQLite.java:84) ~[BetterRTP-3.2.0.jar:?]
        at me.SuperRonanCraft.BetterRTP.references.rtpinfo.CooldownHandler.lambda$load$0(CooldownHandler.java:41) ~[BetterRTP-3.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-280]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Paper-280]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Paper-280]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: me.RonanCraft.Pueblos.resources.files.FileOther$FILETYPE
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-280]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-280]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 8 more
```
**How To Reproduce**:

Run my server setup, /stop, replace with new spigot jar, start up with new jar and read console.

**Expected Behavior**:

A smooth upgrade, not an exception error.

**Screenshots/Error Log**:

see above
**Additional Context**:

Everything else seems to have gone fine, rolling back to previous dir and jar and starting the server up works fine.

**Comment by mibby** [comment]
Can also confirm the error existing with 3.2.0. The jar also rose from 269KB to 2.1MB so perhaps it's shading in stuff incorrectly.

```
[04:27:49] [Craft Scheduler Thread - 15 - BetterRTP/WARN]: [BetterRTP] Plugin BetterRTP v3.2.0 generated an exception while executing task 3413
java.lang.NoClassDefFoundError: me/RonanCraft/Pueblos/resources/files/FileOther$FILETYPE
	at me.SuperRonanCraft.BetterRTP.references.database.SQLite.load(SQLite.java:84) ~[BetterRTP-3.2.0.jar:?]
	at me.SuperRonanCraft.BetterRTP.references.rtpinfo.CooldownHandler.lambda$load$0(CooldownHandler.java:41) ~[BetterRTP-3.2.0.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Purpur-1394]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Purpur-1394]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: me.RonanCraft.Pueblos.resources.files.FileOther$FILETYPE
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:148) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Purpur-1394]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 8 more
```

```
[04:27:50] [Craft Scheduler Thread - 29 - BetterRTP/ERROR]: [BetterRTP] Couldn't execute MySQL statement: 
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "null": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:1012) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.core.DB.newSQLException(DB.java:1024) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.core.DB.throwex(DB.java:989) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.core.DB.prepare(DB.java:257) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[patched_1.17.1.jar:git-Purpur-1394]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[patched_1.17.1.jar:git-Purpur-1394]
	at me.SuperRonanCraft.BetterRTP.references.database.DatabaseCooldowns.getCooldown(DatabaseCooldowns.java:52) ~[BetterRTP-3.2.0.jar:?]
	at me.SuperRonanCraft.BetterRTP.references.rtpinfo.CooldownHandler.loadPlayer(CooldownHandler.java:110) ~[BetterRTP-3.2.0.jar:?]
	at me.SuperRonanCraft.BetterRTP.player.events.Join.lambda$event$0(Join.java:17) ~[BetterRTP-3.2.0.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) [patched_1.17.1.jar:git-Purpur-1394]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Purpur-1394]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Purpur-1394]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by SuperRonanCraft** [comment]
> Can also confirm the error existing with 3.2.0. The jar also rose from 269KB to 2.1MB so perhaps it's shading in stuff it shouldn't be.

Oh my god, this is a nasty bug. Ima be uploading a hot fix for both the large file size and the file issue O_O
Thank you for letting me know!

**Comment by mrfloris** [comment]
Don't worry, this is why we test things first :) Happens. Thank you for the swift follow up.

**Comment by SuperRonanCraft** [comment]
> Don't worry, this is why we test things first :) Happens. Thank you for the swift follow up.

HA! I did! just that Pueblos was loaded in my test server and both plugins use super similar file management systems xDD

Anyways, this has been patched in 3.2.1... hopefully ;)

**Comment by mrfloris** [comment]
Did not fix

```
[15:30:43 WARN]: [BetterRTP] Plugin BetterRTP v3.2.1 generated an exception while executing task 75
java.lang.NoClassDefFoundError: me/RonanCraft/Pueblos/resources/files/FileOther$FILETYPE
        at me.SuperRonanCraft.BetterRTP.references.database.SQLite.load(SQLite.java:84) ~[BetterRTP-3.2.1.jar:?]
        at me.SuperRonanCraft.BetterRTP.references.rtpinfo.CooldownHandler.lambda$load$0(CooldownHandler.java:41) ~[BetterRTP-3.2.1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-280]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Paper-280]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Paper-280]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: me.RonanCraft.Pueblos.resources.files.FileOther$FILETYPE
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-280]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-280]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 8 more
```
